-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 09, 2024 at 06:37 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `corememories`
--

-- --------------------------------------------------------

--
-- Table structure for table `islandcontents`
--

CREATE TABLE `islandcontents` (
  `islandContentID` int(4) NOT NULL,
  `islandOfPersonalityID` int(4) NOT NULL,
  `image` varchar(50) DEFAULT NULL,
  `content` varchar(1500) NOT NULL,
  `color` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `islandcontents`
--

INSERT INTO `islandcontents` (`islandContentID`, `islandOfPersonalityID`, `image`, `content`, `color`) VALUES
(1, 1, 'assets/gif/fam1.gif', 'My family, the Aguilar-Lorio family, is a simple yet loving family of seven. I have four siblings—three brothers and one sister—and we always treasure the time we spend together. As the eldest among my siblings, I do my best to guide and support them in any way I can.\r\n\r\nApart from my immediate family, I also cherish my extended family on both my father’s and mother’s sides. Both families are kind-hearted, cheerful, and always ready to help one another. We often come together during special occasions, such as Christmas, New Year, and other meaningful celebrations, which bring us closer as one big family.\r\n\r\nMy parents, Mama and Papa, work hard every day to provide for us and to ensure we have what we need. Their sacrifices and love are the foundation of our strength as a family. They have taught us the value of kindness, hard work, and staying united no matter what challenges come our way.\r\n\r\nEven during difficult times, we remain supportive of one another. We find joy in the little things and are grateful for the love we share. I am striving to do my best in life, not only for myself but also for my family, as a way of giving back and honoring their sacrifices. My family is my greatest source of inspiration and my most precious blessing.', 'Red'),
(2, 1, 'assets/gif/fam2.gif', 'Our family has a beloved dog named Panda. His name was inspired by his black and white fur, resembling a panda bear. When he was a puppy, he was incredibly cute, but now that he’s grown, he’s become so playful that he sometimes acts like he’s the boss—just kidding! Panda is a kind and cheerful dog, although he can be a bit aggressive when our youngest sibling teases him. Despite that, we consider him part of the family, and without him, our home would feel incomplete.\r\n\r\nPanda knows his name and always greets me with a wagging tail when I come home from school. He runs up to me as if he’s checking in or asking how my day went. He brings so much joy to our lives and helps take away the stress of everyday life.\r\n\r\nWe also have a cat named Mingming, who is just as special to us. Mingming is considered a lucky cat, as our aunt says cats with seven colors bring good fortune. Mingming has black, gray, gold, orange, yellow, brown, and white fur—a beautiful combination. Like Panda, we treat Mingming as part of the family, and we love them both dearly. They bring happiness to our lives and make our home even more lively.', 'Red'),
(3, 1, 'assets/gif/fam3.gif', 'My boyfriend, Theoven, is a very important part of my life and my family. He is my strength and inspiration. There are many times when I doubt myself, but he is always by my side, believing in me and reminding me that I can do it. He constantly encourages me to trust myself and to be stronger in facing challenges.\r\n\r\nHe is always there to help me, especially when I get emotional over my coding or programming tasks that keep running into errors. He lifts my spirits and reminds me that I can overcome those obstacles. When I need to go somewhere unfamiliar, he guides me. And when I have exams but struggle to find time to create a reviewer, he steps in and makes one for me.\r\n\r\nTheoven is my rock, always there to support me. He even visits our home, bringing food to share with my family and bonding with them. His care and effort mean so much to me, and I feel so lucky to have him in my life.', 'Red'),
(4, 2, 'assets/gif/frenny1.gif', 'My church friends, whom I met way back in Grade 11, hold a special place in my heart. They are the ones I shared tears, laughter, joy, and celebrations with. Now, we are pursuing different paths, studying in schools like PUP, BSU, T.I., and TCC. Despite being in different fields, we are united by our dreams and shared determination.\r\n\r\nOur conversations often revolve around academics—how we struggle, how we motivate each other, and how we help one another overcome challenges. I am taking IT, while my friends are in various courses like Education, Accountancy, Engineering, and Psychology. Though our career paths differ, we are united by one goal: to achieve success, help our families, and create better lives for ourselves.\r\n\r\nWe often dream of having our own cars, houses, and a comfortable life. We aim to rise above hardships and fulfill the dreams we had as children. Our primary goal is to give back to our families and support them. We jokingly call ourselves “future rich titas,” but deep down, we are serious about making those dreams come true together.', 'Red'),
(5, 2, 'assets/gif/frenny2.gif', 'They are my \"Vestiez\" friends, and our friendship started unexpectedly through a foundation that helps support us in our education. I feel truly happy and blessed to have them in my life, as they have become a source of inspiration and motivation for me.\r\n\r\nOur most cherished bonding moment is when we visit places together, such as Manila and the Mall of Asia. These moments are filled with laughter, stories, and unforgettable memories. Even when we are apart, we stay connected online through chats, updates, and playful banter. Their presence, whether virtual or in person, always brings me comfort and joy.\r\n\r\nWhat I value most about our friendship is how much I learn from them. They share their experiences about academics, their sacrifices, and the challenges they’ve overcome. Their determination to rise above life’s struggles inspires me to keep pushing forward.\r\n\r\nWe all have a shared dream: to succeed not only for ourselves but also to give back and support our families. Together, we aim to create better futures, and I am grateful to have friends who share the same passion and drive. Their stories remind me that no matter how tough life gets, having people who genuinely care about you makes the journey worthwhile. Our friendship is one of the greatest blessings in my life, and I treasure every moment we share.', 'Pink'),
(6, 2, 'assets/gif/frenny3.gif', 'They are my college buddies, and they are some of the kindest and most cheerful people I know. Since I am naturally a quiet person, they bring out my playful and lively side. I feel truly happy and blessed to have them in my life, as they are the ones I spend my classes with at PUP.\r\n\r\nWe all have different goals in life, but being with them makes everything feel lighter. I don’t feel any pressure when I’m around them. No matter what happens, they remind me that as long as I’m living happily, life is already worth it. My friends are simple yet full of fun, and their energy always brightens my day.\r\n\r\nUnexpectedly, I discovered traits in them that I didn’t expect. For instance, Tyn, who I initially thought was shy, turned out to be cheerful, playful, and loves to joke around. It’s these little surprises that make our friendship more enjoyable and meaningful.\r\n\r\nI am grateful to spend every class with them, as they not only bring happiness but also help me with academics. Through them, I’ve realized that I shouldn’t pressure myself too much. Life is a once-in-a-lifetime journey, and it’s important not to let stress take over. They’ve taught me to trust in God, not to doubt myself, and to believe that everything will fall into place in God’s time.\r\n\r\nHaving them as my friends has been such a blessing, and I’m thankful for the lessons and memories we share. Life feels so much better when you’re surrounded by people who genuinely care and support you.', 'Pink'),
(7, 2, 'assets/gif/frenny4.gif', 'These are my friends from Bicol whom I deeply miss. I was able to spend time with them during my recent vacation from August to September 2024. They have been my friends for 15 years, and every time we meet, our conversations are always deep and long. We have been close since I was in kindergarten, and they remain my best friends until now.\r\n\r\nEven though we are apart, we stay connected through online platforms like Messenger and Facebook. I am so grateful to have met them and to have them as part of my life. They made my childhood incredibly joyful. With them, I experienced playing traditional games like tumbang preso, habulan, pogs, and snakes. We climbed trees, ran around the fields, swam in rivers, and did so many other activities that I now dearly miss.\r\n\r\nLife in Bicol was so much fun when I was a child, and I’m thankful for all those beautiful memories. Spending time with them again recently reminded me of how precious those moments were. We are now on different paths, with some of us pursuing courses in agriculture, education, and more. Despite our differences, we all share the same dream of achieving success.\r\n\r\nI am considering going back to Bicol to bond with them again this coming New Year. It’s always heartwarming to be with people who have been a big part of your journey, and I look forward to creating more memories with them.', 'Pink'),
(8, 2, 'assets/gif/frenny5.gif', 'They are my 5G or \"5 Girls\" from Grade 10, and until now, they remain my friends. I truly miss them and feel blessed to have them in my life. They have always supported me, and we’ve helped each other, especially in academics. We used to review together, bond over meals, share stories, joke around, and so much more.\r\n\r\nBeing with them was always fun because I learned a lot from them. They made everything lighter and more enjoyable, especially during stressful school days. I miss them so much now, as we used to spend so much time together. One of the things I treasure most is how we always hugged each other, showing our care and friendship.\r\n\r\nThey are not just friends but a source of comfort and inspiration in my life. Even though we’re apart now, I carry the memories of our bond with me, and I look forward to the day we can all be together again.', 'Pink'),
(9, 3, 'assets/gif/study1.gif', 'This subject in my 3rd-year college life has become my favorite. It focuses on front-end development, which I really enjoy, and has less PHP involvement—something I find a bit challenging, but manageable. I love learning how to code, even though I’m not yet a pro in this field. I am still in the process of learning and figuring out how each line of code works. I am looking forward to having more time to dive deeper into this subject and improve my skills further.\r\n\r\nThis subject is a huge help for us, especially when we graduate, as the lessons and projects are aligned with the actual demands of the industry. Seeing the works and projects I’ve accomplished through this subject fills me with pride and happiness. Even though I’m not an expert, I gave my best effort to create those projects, and I’m grateful for the learning experience it has given me.\r\n\r\nI am excited to continue learning and developing my skills in web development, knowing that it will open more opportunities for me in the future.', 'Blue'),
(10, 3, 'assets/gif/study2.gif', 'Learning the Multimedia subject has been one of the happiest experiences in my academic journey. There’s no pressure—just pure enjoyment while listening to the professor. This subject is truly enjoyable because it allows us to explore art and creativity without fear or stress.\r\n\r\nI love this subject because it enhances my creative thinking, which is something I genuinely enjoy. I’ve always been passionate about arts. Back then, I mostly focused on traditional arts like drawing, sketching, and poster-making. Now, I’ve transitioned to digital arts, exploring tools like Photoshop, Figma, animations, and more.\r\n\r\nThis shift to digital creativity excites me, as it opens up a world of possibilities for expressing my ideas and learning new techniques. This subject has taught me so much and has given me the opportunity to grow both artistically and technically. I am grateful for this experience, and it inspires me to continue improving my skills in the world of multimedia.', 'Blue'),
(11, 3, 'assets/gif/study3.gif', 'The Data Administration subject is quite challenging for me. While I know how to use SQL queries, I’m not entirely skilled in PHP yet. I still find myself struggling to grasp it fully, perhaps because I’m overwhelmed by the number of programming languages I’ve learned over time.\r\n\r\nThere have been moments where I felt frustrated and even cried because I couldn’t figure out the errors in my code. However, I’m continuously working on improving and understanding it better. Despite the difficulties, I’m grateful that we’re learning this subject because it is essential, especially in business industries where database management is crucial.\r\n\r\nI may not be an expert in this field yet, but I’m taking it one step at a time and doing my best to learn. It’s a tough journey, but I’m determined to keep moving forward and develop my skills further.', 'Blue'),
(12, 4, 'assets/gif/hobby1.gif', 'One hobby that will always be a part of me is drawing and sketching. This is where I can truly express my talent in creating portraits and artwork. It’s a stress-reliever for me, and it brings me joy whenever I’m doing it. Some of my past works include sketches of Fyang Smith, Rabiya Mateo, a random image of a guy, and even my personal inspiration.\r\n\r\nThese past works make me proud because they remind me of what I can create. They show that I have a talent for drawing and sketching. When I was young, I loved joining drawing contests, especially poster-making competitions. I remember back in Grade 3, during Nutrition Month in Bicol, I joined a poster-making contest and won. I was so happy at that time, especially with the prize I received—Flat Tops and Kisses chocolate candies.\r\n\r\nI vividly recall the joy of bringing those chocolates home and sharing them with my grandmother. It was such a simple yet fulfilling moment. These experiences remind me how blessed I am to have this talent and how it has brought happiness to both myself and the people around me.', 'Purple'),
(13, 4, 'assets/gif/hobby2.gif', 'One of my favorite hobbies is sketching gowns. I absolutely love gowns and enjoy watching beauty pageants like Miss Universe. I admire how stunning the candidates look in their gowns, and while watching, I often find myself sketching designs inspired by their outfits. It’s always been a dream of mine to become a fashion designer because I love creating unique clothing designs.\r\n\r\nI’ve sketched many gown designs over the years, although I’ve lost track of some of them. Some of my sketches were inspired by Rabiya Mateo\'s gowns and those worn by her competitors in Miss Universe. The elegance and creativity of those gowns captivate me, and they fuel my imagination to create my own designs.\r\n\r\nEven now, I still hold on to the hope of fulfilling my dream of becoming a fashion designer someday. I feel blessed to have this talent for sketching and designing beautiful outfits. It brings me so much joy to think about the colors, designs, and styles of gowns that I can bring to life through my sketches.', 'Purple'),
(14, 4, 'assets/gif/hobby3.gif', 'Another hobby that I truly enjoy is calligraphy. There’s something captivating about the art of crafting beautiful, flowing strokes of text. It\'s not just writing—it’s creating art through words. One example of my work is the series of months I created for an Art Appreciation project. The elegance and creativity involved in shaping each letter are what make this hobby so fulfilling.\r\n\r\nI’ve always been drawn to the world of arts, and calligraphy has become one of my favorite ways to express that passion. It requires focus, patience, and a steady hand, but the results are always rewarding. Whether I’m designing a simple quote, a greeting card, or decorative headings, I find joy in every line and curve I create.\r\n\r\nCalligraphy also allows me to relax and de-stress. It’s a calming activity that combines creativity and mindfulness, helping me focus on the beauty of the present moment. This hobby inspires me to keep improving and exploring new techniques and styles.\r\n\r\nFor me, calligraphy isn’t just about creating aesthetically pleasing text—it’s also about finding beauty in simplicity and appreciating the effort that goes into every stroke. It’s a skill I love and will continue to cherish as part of my creative journey.', 'Purple');

-- --------------------------------------------------------

--
-- Table structure for table `islandsofpersonality`
--

CREATE TABLE `islandsofpersonality` (
  `islandOfPersonalityID` int(4) NOT NULL,
  `name` varchar(40) NOT NULL,
  `shortDescription` varchar(500) DEFAULT NULL,
  `longDescription` varchar(1500) DEFAULT NULL,
  `color` varchar(10) DEFAULT NULL,
  `image` varchar(50) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `islandsofpersonality`
--

INSERT INTO `islandsofpersonality` (`islandOfPersonalityID`, `name`, `shortDescription`, `longDescription`, `color`, `image`, `status`) VALUES
(1, 'Family Island', 'Welcome to Family Island! Take a look at my family: the Aguilar-Lorio Family from both my mother’s and father’s sides, my dog who is a cherished part of our family, and lastly, my inspiration.', 'Family is the foundation of my strength, the core of my identity, and the greatest source of my joy. The Aguilar-Lorio Family, composed of loved ones from both my mother’s and father’s sides, represents a legacy of love, resilience, and unity. Each member plays a significant role, and together, we create a bond that no distance or challenge can break.\r\n\r\nMy dog, Panda, is more than just a pet; he is a beloved part of our family. His presence brings a unique warmth to our home, and his loyalty and cheerful demeanor remind us daily of the beauty of unconditional love. Panda’s simple yet profound way of connecting with us makes him irreplaceable—a true companion who has carved his place in our hearts.\r\n\r\nLastly, there is my inspiration—a person who embodies hope, motivation, and unwavering support. This inspiration is a guiding light, lifting me during moments of doubt and encouraging me to keep going no matter how tough life gets. Through their belief in me, I am reminded to strive for my dreams and embrace life’s challenges with courage and faith.\r\n\r\nThis is my Family Island—a place where love, loyalty, and inspiration thrive, shaping me into the person I am and the person I strive to become.', 'Red', 'assets/gif/familyIsland.gif', NULL),
(2, 'Friend Island', 'Welcome to Friend Island, a place where I cherish meaningful friendships from Bicol, Batangas and Manila. Though distance separates us, we stay connected online. Take a look at the memories I’ve made with friends who bring happiness, positivity, and true connection into my life!', 'Friendship is a treasure that transcends time and distance, a bond that weaves its way into the fabric of our lives, creating moments of joy and shared dreams. My Friend Island is a collection of cherished connections from Bicol, Batangas, and Manila—places where I’ve formed relationships that have shaped my journey and made life more meaningful.\r\n\r\nEach friendship holds a unique story, built on trust, laughter, and unwavering support. Despite the miles that separate us, our hearts remain close, connected by the magic of shared memories and the power of modern communication. We navigate life together, exchanging updates, offering encouragement, and sharing in each other\'s successes and challenges.\r\n\r\nFrom childhood games in the fields of Bicol to late-night talks about our aspirations in Manila, these friendships are a reminder of the beauty of human connection. They are my source of happiness and positivity, grounding me when life feels overwhelming and lifting me when I need strength. Each friend represents a different chapter of my life, bringing their unique perspective and energy into our bond.\r\n\r\nThese friendships have taught me the value of loyalty, the joy of shared experiences, and the importance of keeping connections alive, no matter the distance. They remind me that life’s greatest wealth lies not in material things but in the relationships we nurture. On this Friend Island, I find solace, inspiration, and a sense of belonging that fuels my journey forward.', 'Pink', 'assets/gif/friendIsland.gif', NULL),
(3, 'Study Island', 'Welcome to Study Island, where I share my journey as a 3rd-year BSIT student at PUP Sto. Tomas Branch. Take a look at my progress as I learn coding and programming while working to make my family proud and build a brighter future.', 'Study Island is a glimpse into my life as a 3rd-year Bachelor of Science in Information Technology (BSIT) student at PUP Sto. Tomas Branch. This journey is a blend of challenges, victories, and lessons that shape me into a more skilled and resilient individual.\r\n\r\nEach line of code represents more than an academic task—it’s a step toward achieving my dreams. Programming is exciting yet challenging, testing my patience and creativity. Errors and bugs often frustrate me, but overcoming them reminds me of the value of perseverance.\r\n\r\nAmong my subjects, web development stands out as a favorite. It allows me to explore front-end technologies, fostering creativity and practicality. Multimedia, another cherished subject, enhances my artistic side, combining my love for art with technology.\r\n\r\nHowever, not everything comes easily. Data administration is a tough subject, especially with PHP. Despite the struggle, I see its importance in the industry and strive to improve.\r\n\r\nThis journey is deeply personal. It’s about making my family proud and creating a better future. Their support fuels my determination to push through every obstacle. Study Island is a testament to my growth, reflecting my commitment to learning, evolving, and achieving.', 'Blue', 'assets/gif/studyIsland.gif', NULL),
(4, 'Hobby Island', 'Welcome to Hobby Island, a space for all the things I love—drawing, sketching, reading books, singing, and more. Take a look at my highlighted hobbies that spark my creativity and bring joy to my everyday life!', 'Hobby Island is a space where my passions come to life. Drawing, sketching, gown design, and calligraphy are more than just activities; they are expressions of creativity and moments of joy.\r\n\r\nDrawing has always been close to my heart, allowing me to express myself through portraits and random sketches. I remember winning a poster-making contest in Grade 3, and the joy it brought me, especially when I shared my prize with my grandmother. These experiences inspire me to continue honing my craft.\r\n\r\nDesigning gowns is another passion of mine, inspired by beauty pageants like Miss Universe. I dream of becoming a fashion designer, creating unique pieces that reflect elegance and creativity. Sketching gowns worn by figures like Rabiya Mateo fuels my imagination and brings my designs to life.\r\n\r\nCalligraphy is a calming hobby that combines art and mindfulness. Crafting each stroke of text is a way for me to express creativity while finding beauty in simplicity. One of my favorite projects was creating a series of months for an Art Appreciation class, where I focused on the elegance of written text.\r\n\r\nHobby Island is where these passions allow me to grow creatively, reflecting the joy and fulfillment I find in expressing myself through art.', 'Purple', 'assets/gif/hobbyIsland.gif', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `islandcontents`
--
ALTER TABLE `islandcontents`
  ADD PRIMARY KEY (`islandContentID`);

--
-- Indexes for table `islandsofpersonality`
--
ALTER TABLE `islandsofpersonality`
  ADD PRIMARY KEY (`islandOfPersonalityID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `islandcontents`
--
ALTER TABLE `islandcontents`
  MODIFY `islandContentID` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;

--
-- AUTO_INCREMENT for table `islandsofpersonality`
--
ALTER TABLE `islandsofpersonality`
  MODIFY `islandOfPersonalityID` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
